[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.113.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# [context.split1]
# command = "hugo --gc --minify --enableGitInfo"

# [context.split1.environment]
# HUGO_VERSION = "0.69.2"
# HUGO_ENV = "production"

# [context.deploy-preview]
# command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

# [context.deploy-preview.environment]
# HUGO_VERSION = "0.69.2"

# [context.branch-deploy]
# command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

# [context.branch-deploy.environment]
# HUGO_VERSION = "0.69.2"

# [context.next.environment]
# HUGO_ENABLEGITINFO = "true"

# Bundle/minify static assets
[build.processing]
skip_processing = false
[build.processing.css]
bundle = true
minify = false
[build.processing.js]
bundle = true
minify = false
[build.processing.html]
pretty_urls = true
[build.processing.images]
compress = true

# Add cache-control headers for static files
[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "public, s-max-age=604800"
[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, s-max-age=604800"
[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, s-max-age=604800"